# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=140)),
                ('likes', models.IntegerField(default=0)),
                ('tweeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tweets', to='tweet.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hashtag',
            unique_together=set([('tag',)]),
        ),
    ]
