# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
        ('tweetpost', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateTimeField(auto_now_add=True)),
                ('liked_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='tweetpost.Tweet')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to='tweet.UserProfile')),
            ],
        ),
    ]
